name: BugLocalization
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.7.6
  - bs4=4.11.1
  - anaconda::nltk
  - pandas=1.3.5
  - lxml=4.9.1
  - pytorch=1.12.1
  - transformers=4.24.0
  - openjdk=11
  - maven=3.9.6
